name: smart_assistant_app
description: A Flutter web application for a smart assistant.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
